# Javier's speeds
JAVIER_SPEED = 4
JAVIER_SPEED_BAD_SHAPE = 6
JAVIER_SPEED_C51 = 8

# Andreina's speeds
ANDREINA_SPEED = JAVIER_SPEED + 2
ANDREINA_SPEED_BAD_SHAPE = JAVIER_SPEED_BAD_SHAPE + 2
ANDREINA_SPEED_C51 = JAVIER_SPEED_C51 + 2

# Graph Constants
GRAPH_SIZE = 25
GRAPH_AVENUE_LOW_LIMIT = 50
GRAPH_AVENUE_HIGH_LIMIT = 55
GRAPH_STREET_LOW_LIMIT = 10
GRAPH_STREET_HIGH_LIMIT = 15

# Edge Constants
LAST_STREET = 14
LAST_AVENUE = 54
BEGINNING_STREET_BAD_SHAPE = 12
HIGH_TRAFFIC_AVENUE = 51
