# Config Variable names
JAVIER_SPEED_CONFIG = "JAVIER_SPEED"
JAVIER_SPEED_BAD_SHAPE_CONFIG = "JAVIER_SPEED_BAD_SHAPE"
JAVIER_SPEED_C51_CONFIG = "JAVIER_SPEED_C51"
ANDREINA_PACE_DIFFERENCE_CONFIG = "ANDREINA_PACE_DIFFERENCE"

GRAPH_SIZE_CONFIG = "GRAPH_SIZE"
FIRST_AVENUE_CONFIG = "FIRST_AVENUE"
LAST_AVENUE_CONFIG = "LAST_AVENUE"
FIRST_STREET_CONFIG = "FIRST_STREET"
LAST_STREET_CONFIG = "LAST_STREET"

BEGINNING_AVENUE_BAD_SHAPE_CONFIG = "BEGINNING_AVENUE_BAD_SHAPE"
END_AVENUE_BAD_SHAPE_CONFIG = "END_AVENUE_BAD_SHAPE"
HIGH_TRAFFIC_STREET_CONFIG = "HIGH_TRAFFIC_STREET"

JAVIER_HOME_CONFIG = "JAVIER_HOME"
ANDREINA_HOME_CONFIG = "ANDREINA_HOME"
THE_DARKNESS_CLUB_CONFIG = "THE_DARKNESS_CLUB"
LA_PASION_BAR_CONFIG = "LA_PASION_BAR"
MI_ROLITA_BREWERY_CONFIG = "MI_ROLITA_BREWERY"

# Important Locations Strings
JAVIER_HOME_STR = "Javier's Home"
ANDREINA_HOME_STR = "Andreina's Home"
THE_DARKNESS_CLUB_STR = "The Darkness Club"
LA_PASION_BAR_STR = "Bar La Pasión"
MI_ROLITA_BREWERY_STR = "Mi Rolita Brewery"

EMPTY_STRING = ""
